[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
via_ir = true
optimizer = true
optimizer_runs = 200

# [etherscan]
# ethereum = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
chiliz = "${CHILIZ_MAINNET_RPC_URL}"
spicy = "${SPICY_TESTNET_RPC_URL}"
story = "${STORY_MAINNET_RPC_URL}"
